spring.application.name=payment-service
server.port=8083

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

# Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Mensageria
rabbitmq.exchange.name=event.exchange
rabbitmq.queue.payment=payment.queue
rabbitmq.routing.created=event.created
rabbitmq.exchange.payment=payment.exchange
rabbitmq.queue.purchase=purchase.queue
rabbitmq.routing.purchased=ticket.purchased